name: Matplotlib OOB Testing System

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  test-suite:
    runs-on: ubuntu-latest

    steps:
    - name: Pobranie kodu
      uses: actions/checkout@v4

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalacja zależności (OOB)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install numpy

    - name: Testy Funkcjonalne
      run: |
        echo "Uruchamiam testy funkcjonalne..."
        # Zapisuje obrazki do folderu "wyniki_funkcjonalne"
        pytest src/functional_tests/ -v --basetemp=wyniki_funkcjonalne

    - name: Testy Wydajnościowe
      run: |
        echo "Uruchamiam testy wydajnościowe..."
        # Zapisuje obrazki do folderu "wyniki_wydajnosciowe"
        pytest src/performance_tests/ -v -s --basetemp=wyniki_wydajnosciowe

    - name: Zapisz wygenerowane wykresy jako artefakty
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: wygenerowane-wykresy
        # Szukamy obrazków .png i .svg tylko w naszych bezpiecznych folderach!
        path: |
          wyniki_funkcjonalne/**/*.{png,svg}
          wyniki_wydajnosciowe/**/*.png
        retention-days: 5